__title__ = 'pghost'
__description__ = 'Export pelican\'s posts and tags to ghost'
__url__ =  ''
__version__ = '0.1'
__author__ = 'Jay Chung'
__author_email__ = 'ken8203@gmail.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2017 Jay Chung'
